SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic53> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic175> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic225> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic236> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic175> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic20> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic20> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic25> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic225> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic7> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic127> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic95> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic7> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic91> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic108> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic91> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic95> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic131> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic53> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic153> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic204> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic226> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic230> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic96> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic200> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic95> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic205> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic227> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic91> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic200> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic20> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic147> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic127> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic204> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic49> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic205> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic205> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic175> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic222> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic225> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic227> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic224> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic66> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic153> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic17> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic49> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic153> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic17> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic154> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic242> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic153> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic215> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic204> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic91> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic224> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic91> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic153> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic221> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic96> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic158> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic205> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic154> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic236> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic225> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic204> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic127> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic91> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic200> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic225> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic108> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic53> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic204> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic224> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic215> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic225> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic227> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic158> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic222> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic49> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic227> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic227> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic224> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic127> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic53> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic158> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic17> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic242> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic204> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic236> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic158> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic227> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic242> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic175> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic96> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic205> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic175> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic91> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic226> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic53> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

SELECT ?v0 ?v2 ?v3 ?v4 ?v5 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic205> .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v3 <http://schema.org/trailer> ?v4 .
	?v3 <http://schema.org/keywords> ?v5 .
	?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v0 .
	?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .
}

