SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre31> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre131> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre102> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre10> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre137> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre11> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre89> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre130> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre119> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre11> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre4> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre31> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre125> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre4> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre55> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre31> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre129> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre68> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre39> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre131> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre116> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre89> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre130> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre128> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre128> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre11> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre55> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre31> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre97> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre116> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre119> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre76> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre133> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre4> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre90> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre39> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre97> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre116> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre129> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre55> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre90> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre129> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre39> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre73> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre102> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre130> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre14> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre140> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre10> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre131> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre119> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre11> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre90> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre116> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre39> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre53> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre92> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre140> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre102> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre11> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre130> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre129> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre31> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre125> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre4> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre28> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre119> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre137> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre131> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre133> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre92> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre76> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre133> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre130> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre137> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre132> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre55> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre131> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre132> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre119> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre53> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre4> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre10> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre130> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre10> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre68> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre28> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre11> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre11> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre119> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre132> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre76> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre10> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre125> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre90> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre140> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre10> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre55> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre76> .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v0 <http://ogp.me/ns#title> ?v2 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .
	?v0 <http://schema.org/caption> ?v4 .
	?v0 <http://schema.org/description> ?v5 .
	?v1 <http://schema.org/url> ?v6 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v7 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre73> .
}

