SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre73> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre64> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre73> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre73> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre96> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre79> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre131> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre107> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre42> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre73> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre64> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre60> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre100> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre107> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre79> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre30> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre64> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre96> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre73> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre107> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre79> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre79> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre60> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre30> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre73> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre60> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre60> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre96> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre60> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://schema.org/contentRating> ?v1 .
	?v0 <http://schema.org/contentSize> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre105> .
	?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v5 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v6 .
	?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .
}

