SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic245> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic20> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic248> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic193> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic154> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic20> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic71> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic155> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic49> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic92> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic138> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic175> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic7> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic166> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic215> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic70> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic245> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic152> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic92> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic218> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic193> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic31> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic49> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic45> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic218> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic218> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic92> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic20> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic215> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic215> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic154> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic134> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic215> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic248> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic138> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic92> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic138> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic7> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic245> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic70> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic70> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic221> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic105> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic180> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic248> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic31> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic48> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic56> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic105> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic134> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic155> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic138> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic180> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic175> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic92> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic152> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic48> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic144> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic71> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic138> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic71> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic138> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic215> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic144> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic175> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic180> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic29> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic248> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic29> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic166> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic48> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic221> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic245> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic141> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic49> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic45> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic221> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic144> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic152> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic49> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic29> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic7> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic152> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic201> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic215> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic182> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic154> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic1> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic20> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic3> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic105> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic215> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic1> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic45> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic144> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic29> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic245> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic7> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic144> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic70> .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

