SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2353> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1328> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1850> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2378> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1383> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer686> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2064> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer467> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1383> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1680> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1455> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1353> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1680> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1328> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer275> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer467> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1383> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1383> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1680> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer540> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1455> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1353> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1476> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer295> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1455> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer275> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1850> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer275> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1488> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2064> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1488> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer275> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer28> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1353> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1383> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1455> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer540> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1850> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer467> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1476> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer540> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1387> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer295> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1926> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1746> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1387> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer467> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1328> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2091> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1680> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1488> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer275> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer670> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1746> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1987> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer66> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer295> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer457> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1926> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1006> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1746> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer670> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1383> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer886> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1006> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1488> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1850> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1455> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2353> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1006> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer432> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1287> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2378> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1987> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer275> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2064> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1476> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1746> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer686> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer66> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2353> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer686> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2091> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1006> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1746> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer886> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer886> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1926> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer295> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2064> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1746> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer457> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1594> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer28> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer686> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1594> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1387> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer432> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer540> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer7> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v4 .
	?v1 <http://ogp.me/ns#title> ?v5 .
	?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .
}

