SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City110> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City189> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City180> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City189> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City193> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City219> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City139> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City68> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City184> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City184> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City219> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City75> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City68> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City72> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City110> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City75> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City68> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City72> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City63> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City147> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City75> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City56> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City147> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City100> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City193> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City56> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City146> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City72> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City68> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City56> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City185> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City120> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City166> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City120> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City180> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City184> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City209> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City94> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City85> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City75> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City209> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City46> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City209> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City166> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City75> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City75> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City85> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City193> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City193> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City75> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City193> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City209> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City120> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City209> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City193> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City120> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City75> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City189> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City75> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City113> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City9> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City193> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City147> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City185> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City113> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City147> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City75> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City75> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City63> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City100> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City120> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City146> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City185> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City90> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City184> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City49> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City49> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City209> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City113> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City193> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City166> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City110> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City235> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City189> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City180> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City166> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City139> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City26> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City9> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City26> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City219> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City9> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City49> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City75> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City184> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City49> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City193> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City85> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City235> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

SELECT ?v1 ?v2 WHERE {
	<http://db.uwaterloo.ca/~galuc/wsdbm/City166> <http://www.geonames.org/ontology#parentCountry> ?v1 .
	?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product0> .
	?v2 <http://schema.org/nationality> ?v1 .
}

