SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic79> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic176> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic86> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic176> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic79> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic86> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic143> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic176> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic184> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic36> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic115> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic236> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic79> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic17> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic176> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic36> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic184> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic17> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic236> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic176> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic79> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic86> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic21> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic176> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic21> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic86> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic115> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic215> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic115> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic21> .
	?v0 <http://schema.org/caption> ?v2 .
}

