SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic127> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic138> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic73> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic181> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic123> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic227> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic28> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic28> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic67> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic127> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic28> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic71> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic57> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic73> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic123> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic227> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic105> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic71> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic79> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic79> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic181> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic20> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic57> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic127> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic30> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic176> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic138> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic105> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic49> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic228> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic45> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic152> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic67> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic30> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic45> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic57> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic222> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic20> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic139> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic20> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic67> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic197> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic108> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic197> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic45> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic181> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic123> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic19> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic152> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic28> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic211> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic105> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic20> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic187> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic138> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic79> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic135> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic152> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic79> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic181> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic135> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic19> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic227> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic176> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic227> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic108> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic52> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic79> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic135> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic149> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic79> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic49> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic139> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic19> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic181> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic127> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic19> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic71> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic30> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic228> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic73> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic152> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic20> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic57> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic138> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic71> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic181> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic176> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic30> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic149> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic20> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic187> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic127> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic222> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic71> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic138> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic227> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic71> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic228> .
	?v0 <http://schema.org/caption> ?v2 .
}

SELECT ?v0 ?v2 WHERE {
	?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic211> .
	?v0 <http://schema.org/caption> ?v2 .
}

