SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City76> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City176> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City176> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City137> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City35> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City76> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City168> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City16> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City206> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City16> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City20> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City83> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City168> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City83> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City76> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City168> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City16> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City206> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City83> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City206> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City137> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City83> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City16> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City83> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City110> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City76> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City83> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City20> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City110> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

SELECT ?v0 ?v1 ?v3 WHERE {
	?v0 <http://schema.org/jobTitle> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/City168> <http://www.geonames.org/ontology#parentCountry> ?v3 .
	?v0 <http://schema.org/nationality> ?v3 .
}

