SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1251> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1035> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2325> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer912> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer819> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1062> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1721> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2227> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer314> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1560> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer356> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer912> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer698> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer356> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer686> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1560> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer742> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2043> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2028> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1035> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer356> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1062> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2325> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1035> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer729> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer742> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer795> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2028> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1441> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer9> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1721> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1551> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2272> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer795> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1560> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer698> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1560> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer593> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer729> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2028> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1551> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2227> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1251> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1441> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer867> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1251> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer579> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer314> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1514> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1560> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1943> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1943> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer742> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1441> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer819> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer356> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1514> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer9> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1217> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2227> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1035> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer893> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1943> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer99> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer742> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1062> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1062> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer686> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2043> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2272> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer9> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer593> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer729> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2028> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer867> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2043> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1551> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1943> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer99> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1062> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2028> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer593> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer867> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1721> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2325> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2272> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer579> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer686> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1721> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer593> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2028> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer99> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer593> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1035> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2043> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer9> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer867> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer912> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer2227> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9 WHERE {
	?v0 <http://purl.org/goodrelations/includes> ?v1 .
	<http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1268> <http://purl.org/goodrelations/offers> ?v0 .
	?v0 <http://purl.org/goodrelations/price> ?v3 .
	?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .
	?v0 <http://purl.org/goodrelations/validFrom> ?v5 .
	?v0 <http://purl.org/goodrelations/validThrough> ?v6 .
	?v0 <http://schema.org/eligibleQuantity> ?v7 .
	?v0 <http://schema.org/eligibleRegion> ?v8 .
	?v0 <http://schema.org/priceValidUntil> ?v9 .
}

