SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre126> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre136> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre65> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre92> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre126> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre122> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre118> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre136> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre126> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre52> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre92> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre102> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre111> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre114> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre52> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre114> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre136> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre118> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre111> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre126> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre52> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre39> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre118> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre122> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre52> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre102> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre39> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre52> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre102> .
}

SELECT ?v0 ?v1 ?v2 WHERE {
	?v0 <http://purl.org/ontology/mo/conductor> ?v1 .
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre92> .
}

