pid=$(pidof virtuoso-t);
echo "query qbsbm01.txt"; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm01.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm01.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm01.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm01.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm01.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm01.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm01.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm01.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm01.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm01.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm01.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm01.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm01.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm01.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm01.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm01.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm01.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm01.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm01.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm01.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm01.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm01.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm01.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm01.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm01.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm01.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm01.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm01.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm01.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm01.txt 2>&1; 
echo "query qbsbm02.txt"; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm02.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm02.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm02.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm02.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm02.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm02.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm02.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm02.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm02.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm02.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm02.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm02.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm02.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm02.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm02.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm02.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm02.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm02.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm02.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm02.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm02.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm02.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm02.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm02.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm02.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm02.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm02.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm02.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm02.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm02.txt 2>&1; 
echo "query qbsbm03.txt"; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm03.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm03.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm03.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm03.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm03.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm03.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm03.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm03.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm03.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm03.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm03.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm03.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm03.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm03.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm03.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm03.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm03.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm03.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm03.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm03.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm03.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm03.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm03.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm03.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm03.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm03.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm03.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm03.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm03.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm03.txt 2>&1; 
echo "query qbsbm04.txt"; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm04.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm04.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm04.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm04.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm04.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm04.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm04.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm04.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm04.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm04.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm04.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm04.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm04.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm04.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm04.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm04.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm04.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm04.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm04.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm04.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm04.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm04.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm04.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm04.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm04.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm04.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm04.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm04.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm04.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm04.txt 2>&1; 
echo "query qbsbm07.txt"; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm07.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm07.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm07.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm07.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm07.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm07.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm07.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm07.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm07.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm07.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm07.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm07.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm07.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm07.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm07.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm07.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm07.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm07.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm07.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm07.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm07.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm07.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm07.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm07.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm07.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm07.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm07.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm07.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm07.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm07.txt 2>&1; 
echo "query qbsbm08.txt"; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm08.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm08.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm08.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm08.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm08.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm08.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm08.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm08.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm08.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm08.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm08.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm08.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm08.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm08.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm08.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm08.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm08.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm08.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm08.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm08.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm08.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm08.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm08.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm08.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm08.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm08.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm08.txt 2>&1; 
sh ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/BSBM/ qbsbm08.txt ../vos/bin/  > ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_qbsbm08.txt 2>&1; 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS); 
echo $(date +%s%3N) 	 $(cat /proc/${pid}/status |grep VmSize) 	 $(cat /proc/${pid}/status |grep VmRSS)>> ./result/BSBM/LENOVO/VIRTUOSO/BSBM_LENOVO_VIRTUOSO_QUERY_MEM_qbsbm08.txt 2>&1; 
