pid=$(pidof virtuoso-t);
echo "query F1.sparql"; 
bash ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/watdiv160/ F1.sparql ../vos/bin/ /home/anhlt185/experiment/result/watdiv160/LENOVO/VIRTUOSO/watdiv160_LENOVO_VIRTUOSO_QUERY_F1.sparql; 
echo "query F2.sparql"; 
bash ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/watdiv160/ F2.sparql ../vos/bin/ /home/anhlt185/experiment/result/watdiv160/LENOVO/VIRTUOSO/watdiv160_LENOVO_VIRTUOSO_QUERY_F2.sparql; 
echo "query F3.sparql"; 
bash ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/watdiv160/ F3.sparql ../vos/bin/ /home/anhlt185/experiment/result/watdiv160/LENOVO/VIRTUOSO/watdiv160_LENOVO_VIRTUOSO_QUERY_F3.sparql; 
echo "query F4.sparql"; 
bash ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/watdiv160/ F4.sparql ../vos/bin/ /home/anhlt185/experiment/result/watdiv160/LENOVO/VIRTUOSO/watdiv160_LENOVO_VIRTUOSO_QUERY_F4.sparql; 
echo "query F5.sparql"; 
bash ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/watdiv160/ F5.sparql ../vos/bin/ /home/anhlt185/experiment/result/watdiv160/LENOVO/VIRTUOSO/watdiv160_LENOVO_VIRTUOSO_QUERY_F5.sparql; 
echo "query L1.sparql"; 
bash ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/watdiv160/ L1.sparql ../vos/bin/ /home/anhlt185/experiment/result/watdiv160/LENOVO/VIRTUOSO/watdiv160_LENOVO_VIRTUOSO_QUERY_L1.sparql; 
echo "query L2.sparql"; 
bash ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/watdiv160/ L2.sparql ../vos/bin/ /home/anhlt185/experiment/result/watdiv160/LENOVO/VIRTUOSO/watdiv160_LENOVO_VIRTUOSO_QUERY_L2.sparql; 
echo "query L3.sparql"; 
bash ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/watdiv160/ L3.sparql ../vos/bin/ /home/anhlt185/experiment/result/watdiv160/LENOVO/VIRTUOSO/watdiv160_LENOVO_VIRTUOSO_QUERY_L3.sparql; 
echo "query L4.sparql"; 
bash ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/watdiv160/ L4.sparql ../vos/bin/ /home/anhlt185/experiment/result/watdiv160/LENOVO/VIRTUOSO/watdiv160_LENOVO_VIRTUOSO_QUERY_L4.sparql; 
echo "query L5.sparql"; 
bash ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/watdiv160/ L5.sparql ../vos/bin/ /home/anhlt185/experiment/result/watdiv160/LENOVO/VIRTUOSO/watdiv160_LENOVO_VIRTUOSO_QUERY_L5.sparql; 
echo "query S1.sparql"; 
bash ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/watdiv160/ S1.sparql ../vos/bin/ /home/anhlt185/experiment/result/watdiv160/LENOVO/VIRTUOSO/watdiv160_LENOVO_VIRTUOSO_QUERY_S1.sparql; 
echo "query S2.sparql"; 
bash ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/watdiv160/ S2.sparql ../vos/bin/ /home/anhlt185/experiment/result/watdiv160/LENOVO/VIRTUOSO/watdiv160_LENOVO_VIRTUOSO_QUERY_S2.sparql; 
echo "query S3.sparql"; 
bash ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/watdiv160/ S3.sparql ../vos/bin/ /home/anhlt185/experiment/result/watdiv160/LENOVO/VIRTUOSO/watdiv160_LENOVO_VIRTUOSO_QUERY_S3.sparql; 
echo "query S4.sparql"; 
bash ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/watdiv160/ S4.sparql ../vos/bin/ /home/anhlt185/experiment/result/watdiv160/LENOVO/VIRTUOSO/watdiv160_LENOVO_VIRTUOSO_QUERY_S4.sparql; 
echo "query S5.sparql"; 
bash ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/watdiv160/ S5.sparql ../vos/bin/ /home/anhlt185/experiment/result/watdiv160/LENOVO/VIRTUOSO/watdiv160_LENOVO_VIRTUOSO_QUERY_S5.sparql; 
echo "query S6.sparql"; 
bash ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/watdiv160/ S6.sparql ../vos/bin/ /home/anhlt185/experiment/result/watdiv160/LENOVO/VIRTUOSO/watdiv160_LENOVO_VIRTUOSO_QUERY_S6.sparql; 
echo "query VC1.sparql"; 
bash ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/watdiv160/ VC1.sparql ../vos/bin/ /home/anhlt185/experiment/result/watdiv160/LENOVO/VIRTUOSO/watdiv160_LENOVO_VIRTUOSO_QUERY_VC1.sparql; 
echo "query VC2.sparql"; 
bash ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/watdiv160/ VC2.sparql ../vos/bin/ /home/anhlt185/experiment/result/watdiv160/LENOVO/VIRTUOSO/watdiv160_LENOVO_VIRTUOSO_QUERY_VC2.sparql; 
echo "query VC3.sparql"; 
bash ./console/virtuoso/virtuoso_single_query.sh nghecon123 /home/anhlt185/experiment/queries/watdiv160/ VC3.sparql ../vos/bin/ /home/anhlt185/experiment/result/watdiv160/LENOVO/VIRTUOSO/watdiv160_LENOVO_VIRTUOSO_QUERY_VC3.sparql; 
